-- Deprecated: admin and usage tables are now part of supabase/schema/helo.sql.
-- Keep this file only so older setup notes that reference it do not fail.
-- Apply helo.sql as the single source of truth for the normalized schema.
