"use client";

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Download, ArrowLeft, RotateCcw } from 'lucide-react';
import './performance.css';

interface PerformanceMetric {
  name: string;
  score: number;
  feedback: string;
}

interface PerformanceData {
  overallScore: number;
  duration: number;
  messagesCount: number;
  completedAt: string;
  metrics: PerformanceMetric[];
  strengths: string[];
  improvements: string[];
  recommendations: string[];
}

export default function PerformancePage() {
  const router = useRouter();
  const [performanceData, setPerformanceData] = useState<PerformanceData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate loading performance data
    const mockData: PerformanceData = {
      overallScore: 7.8,
      duration: 1245,
      messagesCount: 12,
      completedAt: new Date().toISOString(),
      metrics: [
        {
          name: 'Communication',
          score: 8.2,
          feedback: 'Excellent articulation and clear expression of ideas. Good listening skills demonstrated.',
        },
        {
          name: 'Technical Knowledge',
          score: 7.5,
          feedback: 'Solid understanding of core concepts. Some areas could use deeper exploration.',
        },
        {
          name: 'Problem Solving',
          score: 8.0,
          feedback: 'Demonstrated structured approach to problem analysis. Creative solutions presented.',
        },
        {
          name: 'Confidence',
          score: 7.3,
          feedback: 'Good overall confidence, but could benefit from more assertiveness in conclusions.',
        },
        {
          name: 'Engagement',
          score: 7.9,
          feedback: 'Active participation and enthusiastic responses throughout the interview.',
        },
      ],
      strengths: [
        '✨ Clear and coherent communication style',
        '✨ Strong analytical thinking',
        '✨ Professional and courteous demeanor',
        '✨ Good time management',
      ],
      improvements: [
        '🎯 Provide more specific examples with metrics',
        '🎯 Deepen technical knowledge in specific domains',
        '🎯 Practice public speaking confidence',
        '🎯 Prepare standardized answers for common questions',
      ],
      recommendations: [
        'Review technical documentation for your target role',
        'Practice mock interviews at least 2-3 times per week',
        'Record yourself to improve body language and tone',
        'Study real-world case studies relevant to your field',
      ],
    };

    setTimeout(() => {
      setPerformanceData(mockData);
      setLoading(false);
    }, 1000);
  }, []);

  const formatDuration = (seconds: number) => {
    const hrs = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    return `${hrs}h ${mins}m`;
  };

  const getScoreColor = (score: number) => {
    if (score >= 8.5) return '#4ade80'; // Green
    if (score >= 7) return '#fbbf24'; // Amber
    if (score >= 5) return '#f97316'; // Orange
    return '#ef4444'; // Red
  };

  const getScoreLevel = (score: number) => {
    if (score >= 8.5) return 'Excellent';
    if (score >= 7) return 'Good';
    if (score >= 5) return 'Average';
    return 'Needs Improvement';
  };

  const downloadReport = () => {
    if (!performanceData) return;

    const reportText = `
INTERVIEW PERFORMANCE REPORT
============================

Date: ${new Date(performanceData.completedAt).toLocaleDateString()}

OVERALL SCORE: ${performanceData.overallScore}/10 (${getScoreLevel(performanceData.overallScore)})

SESSION DETAILS:
- Duration: ${formatDuration(performanceData.duration)}
- Messages Exchanged: ${performanceData.messagesCount}

PERFORMANCE METRICS:
${performanceData.metrics.map(m => `
${m.name}: ${m.score}/10
Feedback: ${m.feedback}
`).join('')}

STRENGTHS:
${performanceData.strengths.map(s => `- ${s}`).join('\n')}

AREAS FOR IMPROVEMENT:
${performanceData.improvements.map(i => `- ${i}`).join('\n')}

RECOMMENDATIONS:
${performanceData.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

============================
Generated by AI Interview Platform
    `;

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(reportText));
    element.setAttribute('download', `interview_report_${Date.now()}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  if (loading) {
    return (
      <div className="performance-container loading-state">
        <div className="spinner"></div>
        <p>Analyzing your performance...</p>
      </div>
    );
  }

  if (!performanceData) {
    return (
      <div className="performance-container error-state">
        <h1>Unable to load performance data</h1>
        <button onClick={() => router.push('/interview')} className="btn-primary">
          Try Again
        </button>
      </div>
    );
  }

  return (
    <div className="performance-container">
      {/* Header */}
      <div className="performance-header">
        <button className="btn-back" onClick={() => router.push('/configuration')}>
          <ArrowLeft size={18} />
          Back
        </button>
        <h1>Performance Report</h1>
        <button className="btn-download" onClick={downloadReport}>
          <Download size={18} />
          Download Report
        </button>
      </div>

      <div className="performance-content">
        {/* Overall Score Card */}
        <div className="score-card overall">
          <div className="score-circle">
            <div className="score-value">{performanceData.overallScore}</div>
            <div className="score-max">/10</div>
          </div>
          <div className="score-info">
            <h2>Overall Performance</h2>
            <p className="score-level">{getScoreLevel(performanceData.overallScore)}</p>
            <p className="score-message">
              {performanceData.overallScore >= 8
                ? 'Excellent work! You demonstrated strong interview skills.'
                : performanceData.overallScore >= 7
                ? 'Good performance! Keep practicing to improve further.'
                : 'Continue practicing to enhance your interview skills.'}
            </p>
          </div>
        </div>

        {/* Session Summary */}
        <div className="session-summary">
          <div className="summary-card">
            <div className="summary-label">Duration</div>
            <div className="summary-value">{formatDuration(performanceData.duration)}</div>
          </div>
          <div className="summary-card">
            <div className="summary-label">Responses</div>
            <div className="summary-value">{performanceData.messagesCount}</div>
          </div>
          <div className="summary-card">
            <div className="summary-label">Completed</div>
            <div className="summary-value">{new Date(performanceData.completedAt).toLocaleDateString()}</div>
          </div>
        </div>

        {/* Detailed Metrics */}
        <div className="metrics-section">
          <h3>Detailed Metrics</h3>
          <div className="metrics-grid">
            {performanceData.metrics.map((metric, index) => (
              <div key={index} className="metric-card">
                <div className="metric-header">
                  <h4>{metric.name}</h4>
                  <div className="metric-score" style={{ color: getScoreColor(metric.score) }}>
                    {metric.score}
                  </div>
                </div>
                <div className="metric-bar">
                  <div
                    className="metric-fill"
                    style={{
                      width: `${(metric.score / 10) * 100}%`,
                      backgroundColor: getScoreColor(metric.score),
                    }}
                  />
                </div>
                <p className="metric-feedback">{metric.feedback}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Strengths */}
        <div className="section">
          <h3>Your Strengths 💪</h3>
          <div className="strengths-list">
            {performanceData.strengths.map((strength, index) => (
              <div key={index} className="list-item strength">
                <span className="item-icon">✓</span>
                <span className="item-text">{strength}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Improvements */}
        <div className="section">
          <h3>Areas for Improvement 📈</h3>
          <div className="improvements-list">
            {performanceData.improvements.map((improvement, index) => (
              <div key={index} className="list-item improvement">
                <span className="item-icon">→</span>
                <span className="item-text">{improvement}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Recommendations */}
        <div className="section recommendations">
          <h3>Recommendations for Next Interview 🎯</h3>
          <ol className="recommendations-list">
            {performanceData.recommendations.map((rec, index) => (
              <li key={index} className="recommendation-item">
                <span className="recommendation-number">{index + 1}</span>
                <span className="recommendation-text">{rec}</span>
              </li>
            ))}
          </ol>
        </div>

        {/* Action Buttons */}
        <div className="action-buttons">
          <button
            className="btn-primary"
            onClick={() => router.push('/interview')}
          >
            <RotateCcw size={18} />
            Try Another Interview
          </button>
          <button
            className="btn-secondary"
            onClick={() => router.push('/configuration')}
          >
            Back to Configuration
          </button>
        </div>
      </div>
    </div>
  );
}
